#!/usr/bin/env python3
"""Instruction generation (task 2.2): templates + paraphrases, held-out split.

The scene sampler stores the canonical form "drive to the {color} {shape}".
At dataset-build time each episode gets a paraphrase drawn (seed-deterministic)
from TRAIN_TEMPLATES. HELDOUT_TEMPLATES are reserved for evaluation only and
must never appear in a training dataset — the paraphrase-robustness metric
(D6) depends on that separation.

Offline-LLM provenance: both pools were generated by an LLM (Claude) and
frozen here; regeneration is a code change, not a runtime call.
"""

import random

TRAIN_TEMPLATES = [
    'drive to the {color} {shape}',
    'go to the {color} {shape}',
    'head toward the {color} {shape}',
    'navigate to the {color} {shape}',
    'drive over to the {color} {shape}',
    'move to the {color} {shape}',
    'approach the {color} {shape}',
    'go over to the {color} {shape}',
    'drive up to the {color} {shape}',
    'head to the {color} {shape}',
    'make your way to the {color} {shape}',
    'take the rover to the {color} {shape}',
]

HELDOUT_TEMPLATES = [
    'steer toward the {color} {shape}',
    'proceed to the {color} {shape}',
    'roll over to the {color} {shape}',
    'find the {color} {shape} and drive to it',
    'bring the rover to the {color} {shape}',
    'your destination is the {color} {shape}',
]


def paraphrase(color: str, shape: str, seed: int, heldout: bool = False) -> str:
    pool = HELDOUT_TEMPLATES if heldout else TRAIN_TEMPLATES
    tpl = random.Random(seed).choice(pool)
    return tpl.format(color=color, shape=shape)
